"""Neuro-symbolic finding explanation with fact-checking.

Combines a symbolic asset/finding graph (built the same way
``AttackGraphViz`` builds its graph — see
``nexus/reporting/visualizations/attack_graph_viz.py``) with a natural
language explanation generated by an LLM. The "neuro-symbolic" part is not
just "call an LLM and hope" — the LLM's output is parsed for concrete
claims (asset names, finding titles it references) and each claim is
checked against the symbolic graph/finding data before being trusted. Any
claim that can't be verified against the actual input data is surfaced
separately as ``unverified_claims`` rather than silently accepted, so a
report consumer can tell "the model said X" from "X is actually in the
data".

This is deliberately modest: verification is simple substring containment
against known asset names and finding titles, not real semantic entailment
checking. It catches the common failure mode (the LLM inventing an asset or
a finding that doesn't exist, or mis-attributing a real finding to the
wrong asset) without pretending to be a general fact-checking system.
"""
from __future__ import annotations

from typing import Any

import networkx as nx


class NeuroSymbolicExplainer:
    """Explain a set of findings in plain English, then fact-check the
    explanation against the symbolic graph built from those same findings.
    """

    def explain(
        self,
        findings: list[dict[str, Any]],
        llm_router: "Any | None" = None,
    ) -> dict[str, Any]:
        findings = findings or []
        graph = self._build_graph(findings)
        graph_summary = self._graph_summary(graph)

        asset_names = {str(f.get("affected_asset") or "").strip() for f in findings}
        asset_names.discard("")
        finding_titles = {str(f.get("title") or "").strip() for f in findings}
        finding_titles.discard("")

        symbolic_summary = self._symbolic_summary(findings, graph_summary)

        router = llm_router
        if router is None:
            try:
                from nexus.intelligence.llm.router import LLMRouter

                router = LLMRouter()
            except Exception:
                router = None

        llm_text: str | None = None
        if router is not None:
            try:
                prompt = self._build_prompt(findings, asset_names, finding_titles)
                llm_text = router.complete(
                    prompt,
                    system=(
                        "You are a security analyst explaining assessment findings. "
                        "Only reference asset names and finding titles that are "
                        "explicitly given to you -- never invent assets, findings, "
                        "or CVEs that were not in the provided data."
                    ),
                )
            except Exception:
                llm_text = None

        if not llm_text or not str(llm_text).strip() or self._is_unavailable_response(str(llm_text)):
            return {
                "explanation": symbolic_summary,
                "llm_available": False,
                "verified_claims": [],
                "unverified_claims": [],
                "graph_summary": graph_summary,
            }

        verified, unverified = self._fact_check(str(llm_text), asset_names, finding_titles)

        return {
            "explanation": str(llm_text),
            "llm_available": True,
            "verified_claims": verified,
            "unverified_claims": unverified,
            "graph_summary": graph_summary,
        }

    # -- symbolic graph ------------------------------------------------------

    def _build_graph(self, findings: list[dict[str, Any]]) -> "nx.DiGraph":
        """Same construction heuristic as ``AttackGraphViz._build_graph``:
        nodes are ``affected_asset`` values, edges connect assets whose
        findings share a tool "domain" prefix (``tool.split(".")[0]``)."""
        graph: nx.DiGraph = nx.DiGraph()
        asset_domains: dict[str, set[str]] = {}

        for f in findings:
            asset = str(f.get("affected_asset") or "").strip()
            if not asset:
                continue
            graph.add_node(asset)
            tool = str(f.get("tool") or "")
            domain = tool.split(".")[0] if tool else ""
            if domain:
                asset_domains.setdefault(asset, set()).add(domain)

        assets = list(asset_domains.keys())
        for i, a in enumerate(assets):
            for b in assets[i + 1:]:
                if asset_domains[a] & asset_domains[b]:
                    graph.add_edge(a, b)

        return graph

    def _graph_summary(self, graph: "nx.DiGraph") -> dict[str, Any]:
        n_nodes = graph.number_of_nodes()
        n_edges = graph.number_of_edges()
        if n_nodes == 0:
            return {"nodes": 0, "edges": 0, "top_assets": []}

        if n_nodes == 1:
            scores = {next(iter(graph.nodes())): 1.0}
        else:
            try:
                scores = nx.pagerank(graph)
            except Exception:
                scores = {node: 1.0 / n_nodes for node in graph.nodes()}

        top_assets = sorted(scores.items(), key=lambda kv: kv[1], reverse=True)[:5]
        return {
            "nodes": n_nodes,
            "edges": n_edges,
            "top_assets": [{"asset": a, "pagerank": round(s, 4)} for a, s in top_assets],
        }

    def _symbolic_summary(self, findings: list[dict[str, Any]], graph_summary: dict[str, Any]) -> str:
        if not findings:
            return "No findings were provided; there is nothing to explain."

        sev_order = ("critical", "high", "medium", "low", "info")
        counts: dict[str, int] = {s: 0 for s in sev_order}
        for f in findings:
            sev = str(f.get("severity") or "info").lower()
            if sev in counts:
                counts[sev] += 1

        lines = [
            f"{len(findings)} finding(s) across {graph_summary['nodes']} asset(s) "
            f"({graph_summary['edges']} shared-tooling relationship(s) detected)."
        ]
        sev_parts = [f"{counts[s]} {s}" for s in sev_order if counts[s]]
        if sev_parts:
            lines.append("Severity breakdown: " + ", ".join(sev_parts) + ".")
        if graph_summary["top_assets"]:
            top = graph_summary["top_assets"][0]
            lines.append(
                f"Most central asset by pagerank: {top['asset']} "
                f"(score {top['pagerank']})."
            )
        lines.append(
            "(No LLM explanation is available for this run -- this is a "
            "purely symbolic summary derived from the finding data.)"
        )
        return " ".join(lines)

    @staticmethod
    def _is_unavailable_response(text: str) -> bool:
        """``LLMRouter``'s providers don't always raise on failure -- when a
        provider SDK isn't importable, or the underlying API call fails
        (e.g. no Ollama server listening locally, no API key configured),
        they instead return a sentinel string like ``"[ERROR] ..."``,
        ``"[MOCK] ..."``, ``"... Would call API with: ..."`` or
        ``"... Would process: ..."`` rather than propagating an exception.
        Treat those the same as a genuine failure/no-provider-configured
        case so we don't fact-check a placeholder string and call it a real
        explanation."""
        stripped = text.strip()
        sentinels = ("[ERROR]", "[MOCK]")
        if any(stripped.startswith(s) for s in sentinels):
            return True
        markers = ("Would call API with:", "Would process:", "Chat:")
        return any(marker in stripped for marker in markers)

    # -- LLM prompt / fact-check ----------------------------------------------

    def _build_prompt(
        self,
        findings: list[dict[str, Any]],
        asset_names: set[str],
        finding_titles: set[str],
    ) -> str:
        lines = [
            "Explain the overall risk picture presented by the following "
            "security findings in plain English, for a reader who is not a "
            "security expert. Cite specific assets and finding titles by "
            "name where relevant. Only reference assets and finding titles "
            "that appear in the data below -- do not invent, guess, or "
            "generalize beyond what is listed.",
            "",
            "Findings:",
        ]
        for f in findings:
            lines.append(
                f"- asset={f.get('affected_asset', '')!r} "
                f"title={f.get('title', '')!r} "
                f"severity={f.get('severity', 'info')!r}"
            )
        return "\n".join(lines)

    def _fact_check(
        self,
        llm_text: str,
        asset_names: set[str],
        finding_titles: set[str],
    ) -> tuple[list[str], list[str]]:
        """Very simple substring-containment fact check: for each known
        asset/finding-title, note whether the LLM text mentions it
        (verified) — this is the "verified_claims" list. Then look for
        capitalized/quoted-looking tokens in the LLM text that resemble
        asset or finding references but don't match anything known, and
        surface those as "unverified_claims". This intentionally does not
        attempt real NLP/entailment -- it is a defensive substring check,
        not a semantic one.
        """
        verified: list[str] = []
        for asset in asset_names:
            if asset and asset in llm_text:
                verified.append(f"asset:{asset}")
        for title in finding_titles:
            if title and title in llm_text:
                verified.append(f"finding:{title}")

        unverified: list[str] = []
        for candidate in self._extract_candidate_references(llm_text):
            if candidate in asset_names or candidate in finding_titles:
                continue
            if any(candidate in asset or asset in candidate for asset in asset_names):
                continue
            if any(candidate in title or title in candidate for title in finding_titles):
                continue
            unverified.append(candidate)

        return verified, unverified

    @staticmethod
    def _extract_candidate_references(text: str) -> list[str]:
        """Pull out quoted substrings and CVE-shaped tokens as candidate
        factual claims worth checking. Deliberately simple (regex, not
        NLP) -- good enough to catch an LLM naming a specific asset/CVE
        that isn't backed by the input data."""
        import re

        candidates: set[str] = set()
        for m in re.finditer(r'"([^"]{3,80})"|\'([^\']{3,80})\'', text):
            val = (m.group(1) or m.group(2) or "").strip()
            if val:
                candidates.add(val)
        for m in re.finditer(r"\bCVE-\d{4}-\d{4,7}\b", text):
            candidates.add(m.group(0))
        return sorted(candidates)
