"""Branded HTML export — uses the canonical Finding schema."""
from __future__ import annotations

import logging
from html import escape
from pathlib import Path
from typing import Any

from nexus.foundation.schema import normalize_findings, redact_findings

logger = logging.getLogger("nexus.reporting")


class HtmlExport:
    """Export a self-contained, branded HTML findings report."""

    FINDING_FIELDS = [
        "id", "title", "severity", "confidence", "affected_asset",
        "evidence", "remediation", "references", "timestamp", "tool",
    ]

    def export(
        self,
        data: list[Any],
        output: str | Path,
        title: str = "NEXUS-STRIKE Security Assessment Report",
        redact: bool = True,
        include_visualizations: bool = True,
    ) -> Path:
        findings = normalize_findings(data)
        if redact:
            findings = redact_findings(findings)
        rows = self._build_rows(findings)
        summary = self._build_summary(findings)
        visualizations = self._build_visualizations(findings) if include_visualizations else ""
        document = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)}</title>
<style>
  * {{ box-sizing:border-box; margin:0; padding:0 }}
  body {{ font-family:system-ui,-apple-system,'Segoe UI',sans-serif; background:#f5f6fa; color:#172033; padding:2rem }}
  .container {{ max-width:1100px; margin:0 auto }}
  h1 {{ font-size:1.75rem; margin-bottom:.25rem; color:#0a1628 }}
  .subtitle {{ color:#5e6c84; margin-bottom:2rem; font-size:.9rem }}
  .summary-cards {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(140px,1fr)); gap:1rem; margin-bottom:2rem }}
  .card {{ background:#fff; border-radius:8px; padding:1.25rem; box-shadow:0 1px 3px rgba(0,0,0,.08) }}
  .card .count {{ font-size:2rem; font-weight:700 }}
  .card .label {{ font-size:.8rem; color:#5e6c84; text-transform:uppercase; letter-spacing:.5px }}
  .critical .count {{ color:#b42318 }} .high .count {{ color:#b54708 }}
  .medium .count {{ color:#dc6803 }} .low .count {{ color:#175cd3 }} .info .count {{ color:#5e6c84 }}
  .visualizations {{ display:flex; flex-direction:column; gap:1.25rem; margin-bottom:2rem }}
  .viz-block {{ background:#0a0d14; border-radius:8px; padding:1rem; box-shadow:0 1px 3px rgba(0,0,0,.08) }}
  .viz-block h2 {{ color:#e2e8f0; font-size:.85rem; text-transform:uppercase; letter-spacing:.5px; margin-bottom:.75rem }}
  .viz-block svg {{ width:100%; height:auto; display:block }}
  table {{ width:100%; border-collapse:separate; border-spacing:0; background:#fff; border-radius:8px; overflow:hidden; box-shadow:0 1px 3px rgba(0,0,0,.08) }}
  th,td {{ padding:.75rem 1rem; text-align:left; vertical-align:top; border-bottom:1px solid #eef2f8 }}
  th {{ background:#eef2f8; font-weight:600; font-size:.8rem; text-transform:uppercase; letter-spacing:.5px; color:#5e6c84 }}
  tr:last-child td {{ border-bottom:none }}
  .sev-critical,.sev-high {{ color:#b42318; font-weight:600 }}
  .sev-medium {{ color:#dc6803; font-weight:600 }}
  .sev-low {{ color:#175cd3; font-weight:600 }}
  .sev-info {{ color:#5e6c84 }}
  .evidence {{ font-family:'SF Mono','Cascadia Code','Fira Code',monospace; font-size:.8rem; background:#f8f9fc; padding:.5rem; border-radius:4px; white-space:pre-wrap; max-height:120px; overflow-y:auto }}
  .tag {{ display:inline-block; font-size:.7rem; padding:2px 8px; border-radius:10px; font-weight:600 }}
  .tag-critical {{ background:#fef3f2; color:#b42318 }} .tag-high {{ background:#fffaeb; color:#b54708 }}
  .tag-medium {{ background:#fffaeb; color:#dc6803 }} .tag-low {{ background:#eff8ff; color:#175cd3 }}
  .tag-info {{ background:#f8f9fc; color:#5e6c84 }}
  .footer {{ margin-top:2rem; font-size:.8rem; color:#5e6c84; text-align:center }}
</style>
</head>
<body>
<div class="container">
  <h1>{escape(title)}</h1>
  <p class="subtitle">Generated by NEXUS-STRIKE &mdash; {__import__('datetime').datetime.now(__import__('datetime').timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} &mdash; {len(findings)} findings</p>

  {summary}

  {visualizations}

  <table>
    <thead><tr>
      <th>ID</th><th>Severity</th><th>Title</th><th>Asset</th><th>Evidence</th><th>Remediation</th>
    </tr></thead>
    <tbody>{rows}</tbody>
  </table>

  <p class="footer">NEXUS-STRIKE Security Assessment &mdash; Validate findings before remediation.</p>
</div>
</body>
</html>"""
        path = Path(output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(document, encoding="utf-8")
        return path

    def _build_visualizations(self, findings: list[dict]) -> str:
        from nexus.reporting.visualizations.attack_graph_viz import AttackGraphViz
        from nexus.reporting.visualizations.risk_heatmap import RiskHeatmap
        from nexus.reporting.visualizations.timeline_viz import TimelineViz

        blocks = []
        for label, viz in (
            ("Attack Graph", AttackGraphViz()),
            ("Risk Heatmap", RiskHeatmap()),
            ("Finding Timeline", TimelineViz()),
        ):
            try:
                svg = viz.render(findings)
            except Exception:
                logger.warning("visualization %r failed to render; skipping", label, exc_info=True)
                continue
            if svg:
                blocks.append(f'<div class="viz-block"><h2>{escape(label)}</h2>{svg}</div>')

        if not blocks:
            return ""
        return f'<section class="visualizations">{"".join(blocks)}</section>'

    def _build_summary(self, findings: list[dict]) -> str:
        from collections import Counter
        counts = Counter(f.get("severity", "info") for f in findings)
        sevs = ["critical", "high", "medium", "low", "info"]
        cards = "\n".join(
            f'<div class="card {s}"><div class="count">{counts.get(s, 0)}</div><div class="label">{s}</div></div>'
            for s in sevs
        )
        return f'<div class="summary-cards">{cards}</div>'

    def _build_rows(self, findings: list[dict]) -> str:
        if not findings:
            return '<tr><td colspan="6" style="text-align:center;padding:2rem;color:#5e6c84">No findings recorded.</td></tr>'
        rows = []
        for f in findings:
            sev = f.get("severity", "info")
            rows.append(
                f'<tr>'
                f'<td><strong>{escape(f.get("id", ""))}</strong></td>'
                f'<td class="sev-{sev}"><span class="tag tag-{sev}">{sev.upper()}</span></td>'
                f'<td>{escape(f.get("title", ""))}<br><small style="color:#5e6c84">{escape(f.get("tool", ""))}</small></td>'
                f'<td>{escape(f.get("affected_asset", ""))}</td>'
                f'<td><div class="evidence">{escape(f.get("evidence", ""))}</div></td>'
                f'<td>{escape(f.get("remediation", ""))}</td>'
                f'</tr>'
            )
        return "\n".join(rows)