from nexus.agents.base_agent import BaseAgent
from nexus.foundation.schema import STATUS_COMPLETED, STATUS_NO_FINDINGS, STATUS_FAILED, tool_result


class DocWriterAgent(BaseAgent):
    name = "doc_writer_agent"
    description = "support agent for documentation — generates reports, READMEs, and technical documentation"

    async def run(self, task: str, target: str = "", **kwargs) -> dict:
        if not task:
            return tool_result(self.name, target or "unknown", status=STATUS_FAILED, error="No task specified")

        findings = kwargs.get("findings", []) or []
        metadata = kwargs.get("metadata", {}) or {}
        mission_id = metadata.get("mission_id", kwargs.get("mission_id", "assessment"))

        critical = sum(1 for f in findings if f.get("severity") == "critical")
        high = sum(1 for f in findings if f.get("severity") == "high")
        medium = sum(1 for f in findings if f.get("severity") == "medium")
        low = sum(1 for f in findings if f.get("severity") == "low")
        info = sum(1 for f in findings if f.get("severity") == "info")

        lines = []
        lines.append(f"# {mission_id} - Security Assessment Report")
        lines.append("")
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(f"Target: {target or 'N/A'}")
        lines.append(f"Total findings: {len(findings)}")
        lines.append(f"Risk distribution: {critical} critical, {high} high, {medium} medium, {low} low, {info} info")
        lines.append("")
        lines.append("## Findings")
        lines.append("")
        if findings:
            for f in findings:
                lines.append(f"### {f.get('title', 'Untitled')}")
                lines.append(f"- **Severity:** {f.get('severity', 'info')}")
                lines.append(f"- **Confidence:** {f.get('confidence', 'medium')}")
                lines.append(f"- **Asset:** {f.get('affected_asset', target or 'N/A')}")
                if f.get("evidence"):
                    lines.append(f"- **Evidence:** {f['evidence']}")
                if f.get("remediation"):
                    lines.append(f"- **Remediation:** {f['remediation']}")
                lines.append("")
        else:
            lines.append("No findings reported.")
            lines.append("")

        lines.append("## Recommendations")
        lines.append("")
        lines.append("1. Prioritize remediation of critical and high severity findings.")
        lines.append("2. Implement compensating controls for medium severity issues.")
        lines.append("3. Schedule follow-up assessment after remediation.")
        lines.append("")
        lines.append("## Conclusion")
        lines.append("")
        lines.append(f"Assessment completed with {len(findings)} findings. Review recommended actions and timeline.")
        lines.append("")
        lines.append("---")
        lines.append("*Report generated by NEXUS-STRIKE DocWriterAgent*")

        document = "\n".join(lines)

        return tool_result(
            self.name, target or "unknown",
            status=STATUS_COMPLETED,
            findings=[],
            summary=f"Documentation generated for {mission_id}: {len(findings)} findings documented",
            metadata={
                "document": document,
                "mission_id": mission_id,
                "target": target,
                "total_findings": len(findings),
                "severity_counts": {"critical": critical, "high": high, "medium": medium, "low": low, "info": info},
            },
        )
