"""Small, dependency-free execution result cache.

The cache is intentionally scoped to deterministic execution keys generated by
``contracts.execution_cache_key``. It stores JSON-serialisable results only and
uses SQLite so a single process and modest multi-worker deployments can share
results without introducing another service.
"""

from __future__ import annotations

import json
import sqlite3
import time
from pathlib import Path
from typing import Any


class ExecutionCache:
    """TTL-aware SQLite cache with explicit invalidation and bounded reads."""

    def __init__(self, path: str | Path = ".nexus/cache.sqlite3", *, ttl_seconds: int = 3600) -> None:
        if ttl_seconds <= 0:
            raise ValueError("ttl_seconds must be positive")
        self.path = Path(path)
        self.ttl_seconds = ttl_seconds
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    def _connect(self) -> sqlite3.Connection:
        connection = sqlite3.connect(self.path, timeout=5)
        connection.execute("PRAGMA journal_mode=WAL")
        connection.execute("PRAGMA busy_timeout=5000")
        return connection

    def _init_db(self) -> None:
        with self._connect() as db:
            db.execute(
                """CREATE TABLE IF NOT EXISTS execution_cache (
                    cache_key TEXT PRIMARY KEY,
                    payload TEXT NOT NULL,
                    created_at REAL NOT NULL,
                    expires_at REAL NOT NULL
                )"""
            )
            db.execute("CREATE INDEX IF NOT EXISTS idx_execution_cache_expiry ON execution_cache(expires_at)")

    def get(self, cache_key: str) -> Any | None:
        now = time.time()
        with self._connect() as db:
            row = db.execute(
                "SELECT payload, expires_at FROM execution_cache WHERE cache_key = ?",
                (cache_key,),
            ).fetchone()
            if row is None:
                return None
            payload, expires_at = row
            if expires_at <= now:
                db.execute("DELETE FROM execution_cache WHERE cache_key = ?", (cache_key,))
                return None
            return json.loads(payload)

    def put(self, cache_key: str, result: Any) -> None:
        now = time.time()
        payload = json.dumps(result, sort_keys=True, separators=(",", ":"), default=str)
        with self._connect() as db:
            db.execute(
                """INSERT INTO execution_cache(cache_key, payload, created_at, expires_at)
                   VALUES (?, ?, ?, ?)
                   ON CONFLICT(cache_key) DO UPDATE SET
                     payload=excluded.payload,
                     created_at=excluded.created_at,
                     expires_at=excluded.expires_at""",
                (cache_key, payload, now, now + self.ttl_seconds),
            )

    def delete(self, cache_key: str) -> None:
        with self._connect() as db:
            db.execute("DELETE FROM execution_cache WHERE cache_key = ?", (cache_key,))

    def prune(self) -> int:
        with self._connect() as db:
            cursor = db.execute("DELETE FROM execution_cache WHERE expires_at <= ?", (time.time(),))
            return cursor.rowcount

    def clear(self) -> None:
        with self._connect() as db:
            db.execute("DELETE FROM execution_cache")
